### ISSUE TITLE
SDK AndroidTests Runtests Example launches browser on Android Device fails to launch example site

### ISSUE THREAD

**Issue by RoakyWood** [testproject-io/csharp-sdk-examples#5]
Windows 10
Visual Studio Pro. 2019
Latest C# SDK 0.64.0
Latest Test Project Agent

Pixel 3 XL
Android 9
Device is Visible to TestProject
Developer Settings enabled
USB Debugging Enabled

Result:
1. Flashes Appium Settings
2. Browser Launches. Shows **data;** in search/URL window at top of device browser
3. Test does not run as expected
4. Error message: _OneTimeSetUp: TestProject.SDK.Exceptions.FailureException : Failed to start development session, org.openqa.selenium.SessionNotCreatedException: Failed to initialize Appium_Android_Chrome session on UDID after 4/3 attempts._
![C# Android SDK TestProject 3](https://user-images.githubusercontent.com/51122093/94957986-c2977280-04bc-11eb-888a-b3fbf0d31334.png)
![C# Android SDK TestProject 2](https://user-images.githubusercontent.com/51122093/94957683-29685c00-04bc-11eb-822b-7fbd3a883d7e.png)
![C# Android SDK TestProject 1](https://user-images.githubusercontent.com/51122093/94957685-2a998900-04bc-11eb-983a-41534e241844.png)

**Comment by mstrelex** [comment]
Hi @RoakyWood ,

Could you please send us your Agent logs to support@testproject.io?

Thanks.

**Comment by RoakyWood** [comment]
[MobileLog.zip](https://github.com/testproject-io/csharp-sdk-examples/files/5320159/MobileLog.zip)

Having a similar problem with iOS.

Note, we can directly connect from Test Project to either device and record/playback with TestProject  without problem.

Thanks!

**Comment by mstrelex** [comment]
**Regarding Android**

The version of Chrome on your device is too old:

```
Webview version: 'Chrome/66.0.3359.158'
session not created","message":"session not created: This version of ChromeDriver only supports Chrome version 85
```

* Upgrade to latest Chrome 85 on your device 
* Under "Development Options" choose Chrome Stable in WebView implementation

**Regarding iOS**

Web Inspector and remote automation on your device are not enabled:

```
2020-10-02 15:19:06.033 [debug] [iOS] Retrieving contexts and views
2020-10-02 15:19:06.033 [debug] [XCUITest] Selecting by url: false 
2020-10-02 15:19:06.033 [debug] [RemoteDebugger] Sending connection key request
2020-10-02 15:19:06.034 [debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 304): 'setConnectionKey'
2020-10-02 15:19:06.034 [debug] [RemoteDebugger] Sending to Web Inspector took 0ms
2020-10-02 15:19:06.034 [debug] [RemoteDebugger] Selecting application
2020-10-02 15:19:06.034 [debug] [RemoteDebugger] No applications currently connected.
2020-10-02 15:19:06.034 [debug] [XCUITest] No web frames found.
2020-10-02 15:19:06.034 [iOS] Could not find any webviews yet, refreshing/retrying
```

Enable in Settings > Safari > Advanced

* Web Inspector
* Remote Automation

**Comment by RoakyWood** [comment]
You are correct! My mistake, the test works fine on Android after updating the Chrome! Apparently the Safari settings worked so iOS is good too! You may close...

**Comment by mstrelex** [comment]
@RoakyWood thanks for the update, closing.
